# Site settings
email: whyhk91@gmail.com
baseurl: /myBlog
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: young Mind
description: Personal Blog
url: "https://younghoonk17.github.io"
twitter_username: 
default_img: "/assets/images/mountain_2000x1200.jpg"

# Profile settings
name: Yhk
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
